language: node_js
sudo: false
node_js:
  - 6
before_script:
  - |
        if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
            true && export CHANGED_FILES=$(git diff --name-only --diff-filter=ACMRT origin/HEAD)
        fi
